name: Create new branch

on: push

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create branch
        run: |
          git checkout -b new-branch
          git push --set-upstream origin new-branch

