name: create a new branch

on:
  push:
    branches: [ main ]
jobs:
  
  
  runs-on: ubuntu-22:04
  steps:
  - uses: actions/checkout@v2
  - name: create a new branch
    run:  git checkout -b dev1.2.5
